### ISSUE TITLE
common functions-files in unique folder.

### ISSUE THREAD

**Issue by aremazeilles** [eurobench/pi_bullet#3]
In walking a walkingComplete folders, several files are repeated. This is not a good practice, as a change in one should be reproduced in another.
I would therefore suggest creating 2 folders:

* one for your function/files that are shared by both pi script
* one for the functions that are more related to eurobench stuffs, like `read_yaml`, `store_vector`, `store_scalar`....

Then your two scripts could add the path to these two folders.
Would you agree?

**Comment by simonePasi** [comment]
I'm agree.
I will change the file system as you suggest in next days.

**Comment by aremazeilles** [comment]
Hello @simonePasi 

I understand that you made the changes as suggested, right? So that we can close that issue, correct?

**Comment by simonePasi** [comment]
Yes correct
